version: '3.8'

services:
  nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt
    command: yarn dev
    depends_on:
      - api
    image: nuxt_dev
    ports:
      - 3000:3000
      - "24678:24678"
    volumes:
      - ./frontend:/app/frontend
      - /frontend/node_modules
    restart: always
    networks:
      - bridge

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: api
    image: api_dev
    ports:
      - "5240:5240"
    volumes:
      - './backend/:/src/'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5240;
    restart: always
    networks:
      - bridge
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rijenth123+
      MYSQL_DATABASE: ASP

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  bridge:
    driver: bridge